// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const countActiveTokens = `-- name: CountActiveTokens :one
SELECT COUNT(*) FROM file_tokens WHERE consumed = FALSE AND expires > unixepoch('now')
`

func (q *Queries) CountActiveTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO file_tokens (token, file, expires, consumed)
VALUES (?, ?, ?, FALSE)
RETURNING id, token, file, expires, consumed
`

type CreateTokenParams struct {
	Token   string
	File    string
	Expires int64
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (FileToken, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Token, arg.File, arg.Expires)
	var i FileToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.File,
		&i.Expires,
		&i.Consumed,
	)
	return i, err
}

const deleteExpired = `-- name: DeleteExpired :exec
DELETE FROM file_tokens WHERE expires < unixepoch('now') OR consumed = TRUE
`

func (q *Queries) DeleteExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpired)
	return err
}

const redeemToken = `-- name: RedeemToken :one
UPDATE file_tokens SET consumed = TRUE
WHERE token = ? AND consumed = FALSE AND expires > unixepoch('now')
RETURNING file
`

// Atomic single-use redemption: marks consumed and returns file path in one statement.
// Prevents TOCTOU race where two concurrent requests could both redeem the same token.
// Returns no rows if token is invalid, expired, or already consumed.
func (q *Queries) RedeemToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, redeemToken, token)
	var file string
	err := row.Scan(&file)
	return file, err
}
